[profile.default]
# Foundry Configuration for Avalanche Disaster Relief Contracts
# Version: 2.0.0
# Network: Avalanche Fuji Testnet

src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"

# Solidity compiler configuration
solc = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = false

# Gas configuration
gas_limit = 8000000
gas_price = 25000000000

# RPC configuration
rpc_endpoints = { fuji = "https://api.avax-test.network/ext/bc/C/rpc" }

# Etherscan configuration for contract verification
[etherscan]
fuji = { key = "${SNOWTRACE_API_KEY}", url = "https://api.snowtrace.io/api" }

# Profile for testing
[profile.test]
verbosity = 2
gas_reports = ["*"]
fuzz_runs = 1000

# Profile for deployment
[profile.deploy]
verbosity = 3
optimizer = true
optimizer_runs = 1000000

# Profile for local development
[profile.local]
verbosity = 3
gas_reports = ["*"]
auto_detect_solc = false

# Dependencies
[dependencies]
forge-std = "^1.7.0"
openzeppelin-contracts = "^5.0.0"

# Remappings for imports
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@forge-std/=lib/forge-std/src/",
    "forge-std/=lib/forge-std/src/"
]

# Formatting configuration
[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"

# Documentation configuration
[doc]
out = "docs"
title = "Avalanche Disaster Relief Network"
book = "book"
homepage = "https://github.com/Aashik1701/Disaster_Relief_Microfunding_Network"
